### ISSUE TITLE
Supply a stable release branch

### ISSUE THREAD

**Issue by rimas-kudelis** [brissone/moodle-qtype_musictheory#23]
The [Git for Administrators](https://docs.moodle.org/31/en/Git_for_Administrators) page describes a rather convenient way to maintain Moodle by checking it out of git. It also has information about installing extensions similarly, which is the way I use.
However, for that to really work well, the extensions in question should have a stable branch for checking out (because you probably don't want to end up with a WIP state of the extension). Yours doesn't, hence this issue.
Please create a `MOODLE_31_STABLE` or similar branch in your repository, and only push changes to that branch upon releasing a new version. Thank you!

**Comment by brissone** [comment]
Hi Rimas,
Thank you for this note - I did create branches for each version (MOODLE_31_STABLE, MOODLE_35_STABLE, etc) since receiving it and will plan on publishing new versions to each branch separately.
Thanks again!
Eric
